name: Run pdk static validation

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Run pdk validate
      uses: puppets-epic-show-theatre/action-pdk-validate@v1
